//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamShaft
    {
        public CamShaft()
        {
            this.Engines = new HashSet<Engine>();
        }
    
        public int CamShaftID { get; set; }
        public string CamShaftManufacturer { get; set; }
        public string CamShaftHPRating { get; set; }
    
        public virtual ICollection<Engine> Engines { get; set; }
    }
}
