//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Final_ProjectEntities : DbContext
    {
        public Final_ProjectEntities()
            : base("name=Final_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CamShaft> CamShafts { get; set; }
        public DbSet<Engine> Engines { get; set; }
        public DbSet<Engine_PistonRings> Engine_PistonRings { get; set; }
        public DbSet<Make> Makes { get; set; }
        public DbSet<manufacturer> manufacturers { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<PistonRing> PistonRings { get; set; }
        public DbSet<Piston> Pistons { get; set; }
        public DbSet<Transmission> Transmissions { get; set; }
        public DbSet<Turbo> Turboes { get; set; }
    }
}
