//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine_PistonRings
    {
        public int EngineID { get; set; }
        public int PistonRingsID { get; set; }
    
        public virtual Engine Engine { get; set; }
        public virtual Engine Engine1 { get; set; }
        public virtual PistonRing PistonRing { get; set; }
    }
}
