//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public Engine()
        {
            this.Engine_PistonRings = new HashSet<Engine_PistonRings>();
            this.Engine_PistonRings1 = new HashSet<Engine_PistonRings>();
            this.CamShafts = new HashSet<CamShaft>();
            this.Pistons = new HashSet<Piston>();
            this.Transmissions = new HashSet<Transmission>();
            this.Turboes = new HashSet<Turbo>();
            this.Models = new HashSet<Model>();
        }
    
        public int EngineID { get; set; }
        public string EngineName { get; set; }
        public string EngineHP { get; set; }
        public string EngineTorque { get; set; }
    
        public virtual ICollection<Engine_PistonRings> Engine_PistonRings { get; set; }
        public virtual ICollection<Engine_PistonRings> Engine_PistonRings1 { get; set; }
        public virtual ICollection<CamShaft> CamShafts { get; set; }
        public virtual ICollection<Piston> Pistons { get; set; }
        public virtual ICollection<Transmission> Transmissions { get; set; }
        public virtual ICollection<Turbo> Turboes { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
