//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer
    {
        public manufacturer()
        {
            this.Makes = new HashSet<Make>();
        }
    
        public int manufacturerID { get; set; }
        public string manufacturerName { get; set; }
    
        public virtual ICollection<Make> Makes { get; set; }
    }
}
