//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PistonRing
    {
        public PistonRing()
        {
            this.Engine_PistonRings = new HashSet<Engine_PistonRings>();
        }
    
        public int PistonRingsID { get; set; }
        public string PistonRingsManufacturer { get; set; }
        public string PistonRingsHPRating { get; set; }
    
        public virtual ICollection<Engine_PistonRings> Engine_PistonRings { get; set; }
    }
}
