//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.Engine1 = new HashSet<Engine1>();
        }
    
        public int CarModelID { get; set; }
        public string CarModelName { get; set; }
        public int MakeID { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual ICollection<Engine1> Engine1 { get; set; }
    }
}
