//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProject2Entities : DbContext
    {
        public FinalProject2Entities()
            : base("name=FinalProject2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarModel> CarModels { get; set; }
        public DbSet<Engine1> Engine1 { get; set; }
        public DbSet<Make> Makes { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<transmission> transmissions { get; set; }
        public DbSet<turbo> turboes { get; set; }
    }
}
