//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine1
    {
        public Engine1()
        {
            this.transmissions = new HashSet<transmission>();
            this.turboes = new HashSet<turbo>();
        }
    
        public int EngineID { get; set; }
        public string EngineName { get; set; }
        public string EngineHPRating { get; set; }
        public string EngineTorque { get; set; }
        public int CarModelID { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual ICollection<transmission> transmissions { get; set; }
        public virtual ICollection<turbo> turboes { get; set; }
    }
}
