//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalAmount
    {
        public int ManufacturerID { get; set; }
        public int MakeID { get; set; }
        public int CarModelID { get; set; }
        public int Engine1ID { get; set; }
        public int TransmissionID { get; set; }
        public int TurboID { get; set; }
        public decimal Price { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual Engine1 Engine1 { get; set; }
        public virtual Make Make { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual transmission transmission { get; set; }
        public virtual turbo turbo { get; set; }
    }
}
