//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Collections.Generic;
    
    public partial class turbo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public turbo()
        {
            this.TotalAmounts = new HashSet<TotalAmount>();
        }
    
        public int TurboID { get; set; }
        public string TurboName { get; set; }
        public string TurboHPRating { get; set; }
        public string TurboTurbineSize { get; set; }
        public Nullable<int> TransmissionID { get; set; }
        public string Price { get; set; }
    
        public virtual transmission transmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalAmount> TotalAmounts { get; set; }
    }
}
