//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject3
{
    using System;
    using System.Collections.Generic;
    
    public partial class turbo
    {
        public int TurboID { get; set; }
        public string TurboName { get; set; }
        public string TurboHPRating { get; set; }
        public string TurboTurbineSize { get; set; }
        public int EngineID { get; set; }
    
        public virtual Engine1 Engine1 { get; set; }
    }
}
