//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildACar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProject4Entities : DbContext
    {
        public FinalProject4Entities()
            : base("name=FinalProject4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Engine1> Engine1 { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<TotalAmount> TotalAmounts { get; set; }
        public virtual DbSet<transmission> transmissions { get; set; }
        public virtual DbSet<turbo> turboes { get; set; }
    }
}
